name: eCommerceApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 14.0
packages:
  ZipyiOS:
    path: /Users/namrata/Downloads/ZipyiOS
targets:
  eCommerceApp:
    type: application
    platform: iOS
    sources:
      - path: eCommerceApp
    dependencies:
      - package: ZipyiOS
    settings:
      base:
        INFOPLIST_FILE: eCommerceApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.eCommerceApp
    info:
      path: eCommerceApp/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight 